services:
  - type: web
    name: cc-store-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/home
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: cc-store-backend
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FILESYSTEM_DISK
        value: public
      - key: BROADCAST_CONNECTION
        value: "null"
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
